# Generated by Django 3.1.1 on 2020-10-31 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_location_name_short'),
        ('photos', '0002_auto_20201018_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('name_zh', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('rank', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50)),
                ('national_park', models.CharField(blank=True, choices=[('taroko', 'Taroko National Park'), ('sheipa', 'Shei-pa National Park'), ('jade', 'Yushan National Park')], max_length=50, null=True)),
                ('list_photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_peaks', to='photos.photo')),
                ('locations', models.ManyToManyField(to='common.Location')),
            ],
        ),
    ]
