# Generated by Django 3.1.1 on 2020-12-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_featuredpeak'),
        ('photos', '0004_photo_default_slug'),
        ('peaks', '0002_auto_20201107_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak',
            name='description',
        ),
        migrations.AlterField(
            model_name='peak',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='A = beginner<br>B = intermediate<br>C = advanced<br>C+ = expert', max_length=50),
        ),
        migrations.AlterField(
            model_name='peak',
            name='height',
            field=models.IntegerField(help_text='Height in meters'),
        ),
        migrations.AlterField(
            model_name='peak',
            name='latitude',
            field=models.DecimalField(decimal_places=5, help_text='Positive number, 5 decimal places', max_digits=8),
        ),
        migrations.AlterField(
            model_name='peak',
            name='list_photo',
            field=models.ForeignKey(help_text="Choose a good photo that's representative of this peak", on_delete=django.db.models.deletion.PROTECT, related_name='list_peaks', to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='peak',
            name='locations',
            field=models.ManyToManyField(help_text='Select any locations this peak falls in or borders. Most peaks have more than one.', to='common.Location'),
        ),
        migrations.AlterField(
            model_name='peak',
            name='longitude',
            field=models.DecimalField(decimal_places=5, help_text='Positive number, 5 decimal places', max_digits=8),
        ),
        migrations.AlterField(
            model_name='peak',
            name='name_zh',
            field=models.CharField(help_text="This peak's Chinese name, i.e. 南湖大山", max_length=255, verbose_name='Name (中文)'),
        ),
        migrations.AlterField(
            model_name='peak',
            name='national_park',
            field=models.CharField(blank=True, choices=[('taroko', 'Taroko National Park'), ('sheipa', 'Shei-pa National Park'), ('jade', 'Yushan National Park')], help_text='If this peak is in a national park, select it here', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='peak',
            name='rank',
            field=models.IntegerField(help_text='Peak rank from 1-100'),
        ),
    ]
