# Generated by Django 3.1.1 on 2020-10-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_tags'),
        ('routes', '0002_route_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routecarouselphoto',
            unique_together={('route', 'photo')},
        ),
    ]
