# Generated by Django 3.1.1 on 2020-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20201018_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
