# Generated by Django 3.1.1 on 2020-10-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20201018_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='transportation_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='transportation_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
