# Generated by Django 3.1.1 on 2020-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20201005_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeitinerary',
            options={'ordering': ['day_no']},
        ),
        migrations.AddField(
            model_name='routeitinerary',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routeitinerary',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routeitinerary',
            name='water_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
