# Generated by Django 3.1.1 on 2020-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20201006_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeitinerarypoint',
            name='type',
            field=models.CharField(blank=True, choices=[('trailhead', 'Trailhead'), ('peak', 'Top 100 peak'), ('cabin', 'Cabin')], max_length=50, null=True),
        ),
    ]
