# Generated by Django 3.1.1 on 2020-10-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('routes', '0004_auto_20201018_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='location',
        ),
        migrations.AddField(
            model_name='route',
            name='locations',
            field=models.ManyToManyField(to='common.Location'),
        ),
    ]
