# Generated by Django 3.1.1 on 2020-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20201006_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitinerary',
            name='rest_name',
            field=models.CharField(default='cabin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routeitinerary',
            name='rest_type',
            field=models.CharField(choices=[('cabin', 'Cabin'), ('campground', 'Campground')], default='cabin', max_length=50),
            preserve_default=False,
        ),
    ]
