# Generated by Django 3.1.1 on 2020-10-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20201031_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabin',
            name='capacity',
        ),
        migrations.AddField(
            model_name='cabin',
            name='booking_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabin',
            name='capacity_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabin',
            name='capacity_tents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
