# Generated by Django 3.1.1 on 2020-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20201031_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='custom_permit_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
