# Generated by Django 3.1.1 on 2020-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20201006_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='route',
            name='np_permit_required',
            field=models.CharField(blank=True, choices=[('taroko', 'Taroko National Park'), ('sheipa', 'Shei-pa National Park'), ('jade', 'Yushan National Park')], max_length=50, null=True),
        ),
    ]
