# Generated by Django 3.1.1 on 2020-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20201006_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='gpx',
            field=models.FileField(blank=True, null=True, upload_to='route_gpx'),
        ),
    ]
