# Generated by Django 3.1.1 on 2020-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20201031_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cabin_status',
            field=models.CharField(blank=True, choices=[('none', 'No cabins'), ('mixed', 'Mixed cabins/camping'), ('full', 'All cabins')], max_length=50, null=True),
        ),
    ]
