# Generated by Django 3.1.1 on 2020-11-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_auto_20201105_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='list_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
