# Generated by Django 3.1.1 on 2020-10-07 14:41

from django.db import migrations, models
import photos.models
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=photos.models.uuid_photo_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('flickr_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('attr_author', models.CharField(blank=True, max_length=255, null=True)),
                ('attr_title', models.CharField(blank=True, max_length=255, null=True)),
                ('attr_link', models.URLField(blank=True, null=True)),
                ('attr_license', models.CharField(blank=True, choices=[('cc0', 'CC0'), ('pdm', 'PDM'), ('cc_by', 'CC BY'), ('cc_by_sa', 'CC BY-SA'), ('cc_by_nc', 'CC BY-NC'), ('cc_by_nd', 'CC BY-ND'), ('cc_by_nc_sa', 'CC BY-NC-SA'), ('cc_by_nc_nd', 'CC BY-NC-ND')], max_length=50, null=True)),
                ('attr_version', models.CharField(blank=True, choices=[('1.0', '1.0'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('4.0', '4.0')], max_length=5, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
