# Generated by Django 3.1.1 on 2020-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20201004_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='attr_version',
            field=models.CharField(blank=True, choices=[('1.0', '1.0'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('4.0', '4.0')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='attr_license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0'), ('pdm', 'PDM'), ('cc_by', 'CC BY'), ('cc_by_sa', 'CC BY-SA'), ('cc_by_nc', 'CC BY-NC'), ('cc_by_nd', 'CC BY-ND'), ('cc_by_nc_sa', 'CC BY-NC-SA'), ('cc_by_nc_nd', 'CC BY-NC-ND')], max_length=50, null=True),
        ),
    ]
