# Generated by Django 3.1.1 on 2020-12-05 08:22

from django.db import migrations, models
import photos.models
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('photos', '0004_photo_default_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='attr_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='attr_license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0'), ('pdm', 'PDM'), ('cc_by', 'CC BY'), ('cc_by_sa', 'CC BY-SA'), ('cc_by_nc', 'CC BY-NC'), ('cc_by_nd', 'CC BY-ND'), ('cc_by_nc_sa', 'CC BY-NC-SA'), ('cc_by_nc_nd', 'CC BY-NC-ND')], max_length=50, null=True, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='attr_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to Original'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='attr_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='attr_version',
            field=models.CharField(blank=True, choices=[('1.0', '1.0'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('4.0', '4.0')], max_length=5, null=True, verbose_name='License Version'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(help_text='A short description for this photo, max 100 characters.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='flickr_id',
            field=models.CharField(blank=True, help_text='Use if adding a photo from Flickr. Leave empty if uploading an image file.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Use if uploading an image file. Leave empty if using a Flickr image.', null=True, upload_to=photos.models.uuid_photo_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, help_text='An optional unique slug for this photo. Use only if explicitly referenced in templates.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=taggit.managers.TaggableManager(help_text="Comma-separated list of tags. These should include any route tags, for instance 'south-2nd'.", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
