# Generated by Django 3.1.1 on 2020-10-07 11:42

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='flickr_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
