# Generated by Django 3.1.1 on 2020-10-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name_short',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
