# Generated by Django 3.1.1 on 2020-11-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peaks', '0002_auto_20201107_1124'),
        ('common', '0003_featuredroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name_override', models.CharField(blank=True, max_length=50, null=True)),
                ('peak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peaks.peak')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
